profiles: dev

server:
  port: 8888

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/dormitory?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待时间
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # 邮件配置（暂时不用，使用时可根据实际情况更改地址）
  mail:
  #host: smtp.189.cn
  #host: smtp.exmail.qq.com
  #port: 587
  #username: reply@kuaihecaishui.com
  #password: Kh123456
  #default-encoding: UTF-8

  # jpa配置

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# mybatis配置
mybatis:
  mapper-locations: classpath*:/mapping/*Mapper.xml
  type-aliases-package: com.dormitory.vo

# 日志配置 输出debug级日志
logging:
  level:
    com.quick.mapper: DEBUG

